class SSMiscUtils play
{    
    //Selaco doesn't support the SendInterfaceEvent function
    //So do a Quicksave instead
    static void PerformSave(Actor owner)
    {
        //The event handler uses the item
        EventHandler.SendNetworkEvent("SimpleSavesSelacoHack");
    }

    //For GZDoom this is set by convar
    //For Selaco this is always false because Selaco doesn't have a working inventory bar
    static bool ShowInInventory()
    {
        return false;
    }
}
