class SaveGem : Inventory
{
    mixin SaveGemInc;
    Default
    {
        +INVENTORY.UNCLEARABLE;
        +INVENTORY.HUBPOWER;
        +INVENTORY.PERSISTENTPOWER;
        +INVENTORY.IGNORESKILL;
        //+INVENTORY.KEEPDEPLETED;
        //+INVENTORY.INVBAR;
        +INVENTORY.FANCYPICKUPSOUND;
        Inventory.InterHubAmount 9999;
        Inventory.MaxAmount 9999;
        Inventory.Icon "ARTIALI1";
        Tag "";
    }
}
